"""empty message

Revision ID: cfce060d4c9f
Revises: 
Create Date: 2021-01-01 16:18:41.471719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfce060d4c9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronmy', sa.String(), nullable=True),
    sa.Column('mic', sa.String(), nullable=True),
    sa.Column('timezone_offset', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statement_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alpaca_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statement_line_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('financial_statement_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['financial_statement_line_id'], ['financial_statement_line.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('financial_statement_line_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('financial_statement_id', sa.Integer(), nullable=False),
    sa.Column('financial_statement_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['financial_statement_id'], ['financial_statement.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_statement_line_id'], ['financial_statement_line.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provided_by', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('figi', sa.String(), nullable=True),
    sa.Column('composite_figi', sa.String(), nullable=True),
    sa.Column('share_class_figi', sa.String(), nullable=True),
    sa.Column('share_class', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['provided_by'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('industry_category', sa.String(), nullable=False),
    sa.Column('industry_group', sa.String(), nullable=False),
    sa.Column('company_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies_executed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('strategy_executed', sa.Integer(), nullable=True),
    sa.Column('executed_on', sa.Integer(), nullable=True),
    sa.Column('order_placed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executed_on'], ['symbol.id'], ),
    sa.ForeignKeyConstraint(['strategy_executed'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statement_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.Enum('fy', 'q1', 'q2', 'q3', 'q4', name='financialstatementperiod'), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('financial_statement_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_statement_line_id'], ['financial_statement_line.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'financial_statement_line_id', 'fiscal_year', 'fiscal_period')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordered_by', sa.Integer(), nullable=True),
    sa.Column('through_strategy', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('order_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['through_strategy'], ['strategies_executed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.Integer(), nullable=True),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('divident_amount', sa.Float(), nullable=False),
    sa.Column('split_coef', sa.Float(), nullable=False),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['vendor'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_prices_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adj_open', sa.Float(), nullable=False),
    sa.Column('adj_high', sa.Float(), nullable=False),
    sa.Column('adj_low', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('adj_volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_prices_intraday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adj_open', sa.Float(), nullable=False),
    sa.Column('adj_high', sa.Float(), nullable=False),
    sa.Column('adj_low', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('adj_volume', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stocks')
    op.drop_table('stock_prices')
    op.drop_table('stock_strategy')
    op.add_column('strategy', sa.Column('create_by', sa.Integer(), nullable=True))
    op.add_column('strategy', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('strategy', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('strategy', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('strategy', sa.Column('name', sa.String(), nullable=False))
    op.add_column('strategy', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'strategy', 'users', ['create_by'], ['id'])
    op.drop_column('strategy', 'time_created')
    op.drop_column('strategy', 'time_updated')
    op.drop_column('strategy', 'strategy_name')
    op.drop_column('strategy', 'strategy_id')
    op.drop_column('strategy', 'strategy_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('strategy_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('strategy_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('strategy', sa.Column('strategy_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('strategy', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'strategy', type_='foreignkey')
    op.drop_column('strategy', 'updated_at')
    op.drop_column('strategy', 'name')
    op.drop_column('strategy', 'id')
    op.drop_column('strategy', 'description')
    op.drop_column('strategy', 'created_at')
    op.drop_column('strategy', 'create_by')
    op.create_table('stock_strategy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_strategy_stock_id_fkey'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.strategy_id'], name='stock_strategy_strategy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_strategy_pkey')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('high', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('low', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('close', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sma_20', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sma_50', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rsi_14', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_prices_stock_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_prices_pkey')
    )
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shortables', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stocks_pkey')
    )
    op.drop_table('stock_prices_intraday')
    op.drop_table('stock_prices_daily')
    op.drop_table('stock_adjustment')
    op.drop_table('orders')
    op.drop_table('financial_statement_fact')
    op.drop_table('strategies_executed')
    op.drop_table('company')
    op.drop_table('symbol')
    op.drop_table('financial_statement_line_sequence')
    op.drop_table('financial_statement_line_alias')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('financial_statement_line')
    op.drop_table('financial_statement')
    op.drop_table('exchange')
    # ### end Alembic commands ###
